window.herbCatalog = [
  {
    slug: "agnimantha",
    name: "Agnimantha",
    scientific: "Premna integrifolia",
    rawLabel: "stem bark",
    description: "We supply premium quality Agnimantha stem bark in raw form for manufacturers, traders, wholesalers & exporters worldwide.",
    forms: ["Stem Bark Whole", "Cut", "Broken", "Powder"],
    packing: ["500g", "1kg", "5kg", "10kg", "25kg", "50kg+"],
    icon: "fa-tree",
    imageBase: "assets/herbs/agnimantha",
    catalogImage: "assets/images/AGNIMANTHA.jpeg"
  },
  {
    slug: "aloe-vera",
    name: "Aloe Vera",
    scientific: "Aloe barbadensis Miller",
    rawLabel: "leaf",
    description: "We supply premium quality Aloe Vera in raw form for manufacturers, traders, wholesalers & exporters worldwide.",
    forms: ["Whole Leaf (Dried)", "Cut", "Broken", "Powder"],
    packing: ["500g", "1kg", "5kg", "10kg", "25kg", "50kg+"],
    icon: "fa-leaf",
    imageBase: "assets/herbs/aloe-vera",
    catalogImage: "assets/images/ALOE VERA.jpeg"
  },
  {
    slug: "amla",
    name: "Amla",
    scientific: "Phyllanthus emblica",
    rawLabel: "fruit",
    description: "We supply premium quality Amla in raw form for manufacturers, traders, wholesalers & exporters worldwide.",
    forms: ["Whole Dried", "Cut", "Broken", "Powder"],
    packing: ["500g", "1kg", "5kg", "10kg", "25kg", "50kg+"],
    icon: "fa-apple-whole",
    imageBase: "assets/herbs/amla",
    catalogImage: "assets/images/AMLA.jpeg"
  },
  {
    slug: "anantmool",
    name: "Anantmool",
    scientific: "Hemidesmus indicus",
    rawLabel: "root",
    description: "We supply premium quality Anantmool in raw form for manufacturers, traders, wholesalers & exporters worldwide.",
    forms: ["Whole Dried", "Cut", "Broken", "Powder"],
    packing: ["500g", "1kg", "5kg", "10kg", "25kg", "50kg+"],
    icon: "fa-grip-lines",
    imageBase: "assets/herbs/anantmool",
    catalogImage: "assets/images/ANANTMOOL.jpeg"
  },
  {
    slug: "arjuna",
    name: "Arjuna",
    scientific: "Terminalia arjuna",
    rawLabel: "stem bark",
    description: "We supply premium quality Arjuna stem bark in raw form for manufacturers, traders, wholesalers & exporters worldwide.",
    forms: ["Whole Dried", "Cut", "Broken", "Powder"],
    packing: ["500g", "1kg", "5kg", "10kg", "25kg", "50kg+"],
    icon: "fa-tree",
    imageBase: "assets/herbs/arjuna",
    catalogImage: "assets/images/ARJUNA.jpeg"
  },
  {
    slug: "ami",
    name: "Ami",
    scientific: "Trachyspermum ammi",
    rawLabel: "seed",
    description: "We supply premium quality Ami seeds in raw form for manufacturers, traders, wholesalers & exporters worldwide.",
    forms: ["Whole Dried", "Cut", "Broken", "Powder"],
    packing: ["500g", "1kg", "5kg", "10kg", "25kg", "50kg+"],
    icon: "fa-seedling",
    imageBase: "assets/herbs/ami",
    catalogImage: "assets/images/AMI.jpeg"
  },
  {
    slug: "ashoka",
    name: "Ashoka",
    scientific: "Saraca asoca",
    rawLabel: "bark",
    description: "We supply premium quality Ashoka bark in raw form for manufacturers, traders, wholesalers & exporters worldwide.",
    forms: ["Whole Dried", "Cut", "Broken", "Powder"],
    packing: ["500g", "1kg", "5kg", "10kg", "25kg", "50kg+"],
    icon: "fa-tree",
    imageBase: "assets/herbs/ashoka",
    catalogImage: "assets/images/ASHOKA.jpeg"
  },
  {
    slug: "ashwagandha",
    name: "Ashwagandha",
    scientific: "Withania somnifera",
    rawLabel: "root",
    description: "We supply premium quality Ashwagandha root in raw form for manufacturers, traders, wholesalers & exporters worldwide.",
    forms: ["Whole Dried", "Cut", "Broken", "Powder"],
    packing: ["500g", "1kg", "5kg", "10kg", "25kg", "50kg+"],
    icon: "fa-grip-lines",
    imageBase: "assets/herbs/ashwagandha",
    catalogImage: "assets/images/ASHWAGANDHA.jpeg"
  },
  {
    slug: "bakuchi",
    name: "Bakuchi",
    scientific: "Psoralea corylifolia",
    rawLabel: "seed",
    description: "We supply premium quality Bakuchi seeds in raw form for manufacturers, traders, wholesalers & exporters worldwide.",
    forms: ["Whole Dried", "Cut", "Broken", "Powder"],
    packing: ["500g", "1kg", "5kg", "10kg", "25kg", "50kg+"],
    icon: "fa-seedling",
    imageBase: "assets/herbs/bakuchi",
    catalogImage: "assets/images/BAKUCHI.jpeg"
  },
  {
    slug: "bhringraj",
    name: "Bhringraj",
    scientific: "Eclipta alba",
    rawLabel: "herb",
    description: "We supply premium quality Bhringraj herb in raw form for manufacturers, traders, wholesalers & exporters worldwide.",
    forms: ["Whole Dried", "Cut", "Broken", "Powder"],
    packing: ["500g", "1kg", "5kg", "10kg", "25kg", "50kg+"],
    icon: "fa-leaf",
    imageBase: "assets/herbs/bhringraj",
    catalogImage: "assets/images/BHRINGRAJ.jpeg"
  },
  {
    slug: "bhumi-amla",
    name: "Bhumi Amla",
    scientific: "Phyllanthus niruri",
    rawLabel: "whole herb",
    description: "We supply premium quality Bhumi Amla whole herb in raw form for manufacturers, traders, wholesalers & exporters worldwide.",
    forms: ["Whole Dried", "Cut", "Broken", "Powder"],
    packing: ["500g", "1kg", "5kg", "10kg", "25kg", "50kg+"],
    icon: "fa-clover",
    imageBase: "assets/herbs/bhumi-amla",
    catalogImage: "assets/images/BHUMI AMLA.jpeg"
  },
  {
    slug: "brahmi",
    name: "Brahmi",
    scientific: "Bacopa monnieri",
    rawLabel: "whole herb",
    description: "We supply premium quality Brahmi whole herb in raw form for manufacturers, traders, wholesalers & exporters worldwide.",
    forms: ["Whole Dried", "Cut", "Broken", "Powder"],
    packing: ["500g", "1kg", "5kg", "10kg", "25kg", "50kg+"],
    icon: "fa-leaf",
    imageBase: "assets/herbs/brahmi",
    catalogImage: "assets/images/BRAHMI.jpeg"
  },
  {
    slug: "chirayata",
    name: "Chirayata",
    scientific: "Swertia chirayita",
    rawLabel: "whole herb",
    description: "We supply premium quality Chirayata whole herb in raw form for manufacturers, traders, wholesalers & exporters worldwide.",
    forms: ["Whole Dried", "Cut", "Broken", "Powder"],
    packing: ["500g", "1kg", "5kg", "10kg", "25kg", "50kg+"],
    icon: "fa-wheat-awn",
    imageBase: "assets/herbs/chirayata",
    catalogImage: "assets/images/CHIRAYATA.jpeg"
  },
  {
    slug: "daruharidra",
    name: "Daruharidra",
    scientific: "Berberis aristata",
    rawLabel: "root",
    description: "We supply premium quality Daruharidra root in raw form for manufacturers, traders, wholesalers & exporters worldwide.",
    forms: ["Whole Dried", "Cut", "Broken", "Powder"],
    packing: ["500g", "1kg", "5kg", "10kg", "25kg", "50kg+"],
    icon: "fa-staff-snake",
    imageBase: "assets/herbs/daruharidra",
    catalogImage: "assets/images/DARUHARIDRA.jpeg"
  },
  {
    slug: "giloy",
    name: "Giloy",
    scientific: "Tinospora cordifolia",
    rawLabel: "whole herb",
    description: "We supply premium quality Giloy whole herb in raw form for manufacturers, traders, wholesalers & exporters worldwide.",
    forms: ["Whole Dried", "Cut", "Broken", "Powder"],
    packing: ["500g", "1kg", "5kg", "10kg", "25kg", "50kg+"],
    icon: "fa-link",
    imageBase: "assets/herbs/giloy",
    catalogImage: "assets/images/GILROY.jpeg"
  },
  {
    slug: "gokhru",
    name: "Gokhru",
    scientific: "Tribulus terrestris",
    rawLabel: "whole herb",
    description: "We supply premium quality Gokhru whole herb in raw form for manufacturers, traders, wholesalers & exporters worldwide.",
    forms: ["Whole Dried", "Cut", "Broken", "Powder"],
    packing: ["500g", "1kg", "5kg", "10kg", "25kg", "50kg+"],
    icon: "fa-certificate",
    imageBase: "assets/herbs/gokhru",
    catalogImage: "assets/images/GOKHRU.jpeg"
  },
  {
    slug: "gudmar",
    name: "Gudmar",
    scientific: "Gymnema sylvestre",
    rawLabel: "whole herb",
    description: "We supply premium quality Gudmar whole herb in raw form for manufacturers, traders, wholesalers & exporters worldwide.",
    forms: ["Whole Dried", "Cut", "Broken", "Powder"],
    packing: ["500g", "1kg", "5kg", "10kg", "25kg", "50kg+"],
    icon: "fa-leaf",
    imageBase: "assets/herbs/gudmar",
    catalogImage: "assets/images/GUDMAR.jpeg"
  },
  {
    slug: "hibiscus",
    name: "Hibiscus",
    scientific: "Hibiscus rosa-sinensis",
    rawLabel: "whole herb",
    description: "We supply premium quality Hibiscus whole herb in raw form for manufacturers, traders, wholesalers & exporters worldwide.",
    forms: ["Whole Dried", "Cut", "Broken", "Powder"],
    packing: ["500g", "1kg", "5kg", "10kg", "25kg", "50kg+"],
    icon: "fa-fan",
    imageBase: "assets/herbs/hibiscus",
    catalogImage: "assets/images/HIBISCUS.jpeg"
  },
  {
    slug: "isabgol",
    name: "Isabgol",
    scientific: "Plantago ovata",
    rawLabel: "husk",
    description: "We supply premium quality Isabgol husk in raw form for manufacturers, traders, wholesalers & exporters worldwide.",
    forms: ["Whole Husk", "Cut Husk", "Broken Husk", "Powder"],
    packing: ["500g", "1kg", "5kg", "10kg", "25kg", "50kg+"],
    icon: "fa-bowl-rice",
    imageBase: "assets/herbs/isabgol",
    catalogImage: "assets/images/ISABGOL.jpeg"
  },
  {
    slug: "jatamansi",
    name: "Jatamansi",
    scientific: "Nardostachys jatamansi",
    rawLabel: "root",
    description: "We supply premium quality Jatamansi root in raw form for manufacturers, traders, wholesalers & exporters worldwide.",
    forms: ["Whole Root", "Cut Root", "Broken Root", "Powder"],
    packing: ["500g", "1kg", "5kg", "10kg", "25kg", "50kg+"],
    icon: "fa-wand-magic-sparkles",
    imageBase: "assets/herbs/jatamansi",
    catalogImage: "assets/images/JATAMANSI.jpeg"
  },
  {
    slug: "kalmegh",
    name: "Kalmegh",
    scientific: "Andrographis paniculata",
    rawLabel: "whole herb",
    description: "We supply premium quality Kalmegh whole herb in raw form for manufacturers, traders, wholesalers & exporters worldwide.",
    forms: ["Whole Herb", "Cut Herb", "Broken Herb", "Powder"],
    packing: ["500g", "1kg", "5kg", "10kg", "25kg", "50kg+"],
    icon: "fa-seedling",
    imageBase: "assets/herbs/kalmegh",
    catalogImage: "assets/images/KALMEGH.jpeg"
  },
  {
    slug: "khadir",
    name: "Khadir",
    scientific: "Acacia catechu",
    rawLabel: "heartwood",
    description: "We supply premium quality Khadir heartwood in raw form for manufacturers, traders, wholesalers & exporters worldwide.",
    forms: ["Whole Pieces", "Cut Pieces", "Broken Pieces", "Powder"],
    packing: ["500g", "1kg", "5kg", "10kg", "25kg", "50kg+"],
    icon: "fa-tree",
    imageBase: "assets/herbs/khadir",
    catalogImage: "assets/images/KHADIR.jpeg"
  },
  {
    slug: "lodhra",
    name: "Lodhra",
    scientific: "Symplocos racemosa",
    rawLabel: "bark",
    description: "We supply premium quality Lodhra bark in raw form for manufacturers, traders, wholesalers & exporters worldwide.",
    forms: ["Whole Bark", "Cut Bark", "Broken Bark", "Powder"],
    packing: ["500g", "1kg", "5kg", "10kg", "25kg", "50kg+"],
    icon: "fa-tree",
    imageBase: "assets/herbs/lodhra",
    catalogImage: "assets/images/LODHRA.jpeg"
  },
  {
    slug: "moringa",
    name: "Moringa",
    scientific: "Moringa oleifera",
    rawLabel: "leaves, pods and seeds",
    description: "We supply premium quality Moringa leaves, pods, seeds & powder in raw form for manufacturers, traders, wholesalers & exporters worldwide.",
    forms: ["Whole Leaves", "Leaf Cut", "Pods Cut", "Leaf Powder"],
    packing: ["500g", "1kg", "5kg", "10kg", "25kg", "50kg+"],
    icon: "fa-leaf",
    imageBase: "assets/herbs/moringa",
    catalogImage: "assets/images/MORINGA.jpeg"
  },
  {
    slug: "mulethi",
    name: "Mulethi",
    scientific: "Glycyrrhiza glabra",
    rawLabel: "roots and sticks",
    description: "We supply premium quality Mulethi roots, sticks, powder & cut form in raw form for manufacturers, traders, wholesalers & exporters worldwide.",
    forms: ["Whole Sticks", "Cut Sticks", "Cut Roots", "Root Powder"],
    packing: ["500g", "1kg", "5kg", "10kg", "25kg", "50kg+"],
    icon: "fa-grip-lines-vertical",
    imageBase: "assets/herbs/mulethi",
    catalogImage: "assets/images/MULETHI.jpeg"
  },
  {
    slug: "nagarmotha",
    name: "Nagarmotha",
    scientific: "Cyperus rotundus",
    rawLabel: "rhizomes",
    description: "We supply premium quality Nagarmotha rhizomes in whole, cut and powder form for manufacturers, traders, wholesalers & exporters worldwide.",
    forms: ["Whole Rhizomes", "Cut Rhizomes", "Cut Pieces", "Powder"],
    packing: ["500g", "1kg", "5kg", "10kg", "25kg", "50kg+"],
    icon: "fa-braille",
    imageBase: "assets/herbs/nagarmotha",
    catalogImage: "assets/images/NAGARMOTHA.jpeg"
  },
  {
    slug: "neem",
    name: "Neem",
    scientific: "Azadirachta indica",
    rawLabel: "leaves, twigs and seeds",
    description: "We supply premium quality Neem leaves, twigs, seeds & powder in raw form for manufacturers, traders, wholesalers & exporters worldwide.",
    forms: ["Whole Leaves", "Twigs / Sticks", "Seeds / Kernels", "Leaf Powder"],
    packing: ["500g", "1kg", "5kg", "10kg", "25kg", "50kg+"],
    icon: "fa-leaf",
    imageBase: "assets/herbs/neem",
    catalogImage: "assets/images/NEEM.jpeg"
  },
  {
    slug: "patala",
    name: "Patala",
    scientific: "Stereospermum suaveolens",
    rawLabel: "bark",
    description: "We supply premium quality Patala bark in raw form for manufacturers, traders, wholesalers & exporters worldwide.",
    forms: ["Whole Dried", "Cut", "Broken", "Powder"],
    packing: ["500g", "1kg", "5kg", "10kg", "25kg", "50kg+"],
    icon: "fa-tree",
    imageBase: "assets/herbs/patala",
    catalogImage: "assets/images/PATALA.jpeg"
  },
  {
    slug: "punarnava",
    name: "Punarnava",
    scientific: "Boerhaavia diffusa",
    rawLabel: "whole herb",
    description: "We supply premium quality Punarnava whole herb in raw form for manufacturers, traders, wholesalers & exporters worldwide.",
    forms: ["Whole Herb", "Cut Herb", "Root Pieces", "Powder"],
    packing: ["500g", "1kg", "5kg", "10kg", "25kg", "50kg+"],
    icon: "fa-seedling",
    imageBase: "assets/herbs/punarnava",
    catalogImage: "assets/images/PUNARNAVA.jpeg"
  },
  {
    slug: "sarpgandha",
    name: "Sarpgandha",
    scientific: "Rauwolfia serpentina",
    rawLabel: "roots",
    description: "We supply premium quality Sarpgandha roots in raw form for manufacturers, traders, wholesalers & exporters worldwide.",
    forms: ["Whole Roots", "Cut Roots", "Root Pieces", "Root Powder"],
    packing: ["500g", "1kg", "5kg", "10kg", "25kg", "50kg+"],
    icon: "fa-staff-snake",
    imageBase: "assets/herbs/sarpgandha",
    catalogImage: "assets/images/SARPGANDHA.jpeg"
  },
  {
    slug: "senna",
    name: "Senna",
    scientific: "Cassia angustifolia",
    rawLabel: "leaves",
    description: "We supply premium quality Senna leaves in raw form for manufacturers, traders, wholesalers & exporters worldwide.",
    forms: ["Whole Leaves", "Cut Leaves", "Broken Leaves", "Leaf Powder"],
    packing: ["500g", "1kg", "5kg", "10kg", "25kg", "50kg+"],
    icon: "fa-leaf",
    imageBase: "assets/herbs/senna",
    catalogImage: "assets/images/SENNA.jpeg"
  },
  {
    slug: "shankhpushpi",
    name: "Shankhpushpi",
    scientific: "Convolvulus pluricaulis",
    rawLabel: "herb",
    description: "We supply premium quality Shankhpushpi herb in raw form for manufacturers, traders, wholesalers & exporters worldwide.",
    forms: ["Whole Herb", "Cut Herb", "Broken Herb", "Powder"],
    packing: ["500g", "1kg", "5kg", "10kg", "25kg", "50kg+"],
    icon: "fa-flower-tulip",
    imageBase: "assets/herbs/shankhpushpi",
    catalogImage: "assets/images/SHANKHPUSHPI.jpeg"
  },
  {
    slug: "shatavari",
    name: "Shatavari",
    scientific: "Asparagus racemosus",
    rawLabel: "roots",
    description: "We supply premium quality Shatavari roots in raw form for manufacturers, traders, wholesalers & exporters worldwide.",
    forms: ["Whole Roots", "Cut Roots", "Root Pieces", "Root Powder"],
    packing: ["500g", "1kg", "5kg", "10kg", "25kg", "50kg+"],
    icon: "fa-grip-lines",
    imageBase: "assets/herbs/shatavari",
    catalogImage: "assets/images/SHATAVARI.jpeg"
  },
  {
    slug: "tagar",
    name: "Tagar",
    scientific: "Valeriana wallichii",
    rawLabel: "roots",
    description: "We supply premium quality Tagar roots in raw form for manufacturers, traders, wholesalers & exporters worldwide.",
    forms: ["Whole Roots", "Cut Roots", "Root Pieces", "Root Powder"],
    packing: ["500g", "1kg", "5kg", "10kg", "25kg", "50kg+"],
    icon: "fa-grip-lines",
    imageBase: "assets/herbs/tagar",
    catalogImage: "assets/images/TAGAR.jpeg"
  },
  {
    slug: "tulsi",
    name: "Tulsi",
    scientific: "Ocimum tenuiflorum",
    rawLabel: "leaves",
    description: "We supply premium quality Tulsi leaves in raw form for manufacturers, traders, wholesalers & exporters worldwide.",
    forms: ["Whole Leaves", "Cut Leaves", "Crushed Leaves", "Leaf Powder"],
    packing: ["500g", "1kg", "5kg", "10kg", "25kg", "50kg+"],
    icon: "fa-leaf",
    imageBase: "assets/herbs/tulsi",
    catalogImage: "assets/images/TULSI.jpeg"
  },
  {
    slug: "varuna",
    name: "Varuna",
    scientific: "Crataeva nurvala",
    rawLabel: "bark",
    description: "We supply premium quality Varuna bark in raw form for manufacturers, traders, wholesalers & exporters worldwide.",
    forms: ["Whole Bark", "Cut Bark", "Bark Pieces", "Bark Powder"],
    packing: ["500g", "1kg", "5kg", "10kg", "25kg", "50kg+"],
    icon: "fa-tree",
    imageBase: "assets/herbs/varuna",
    catalogImage: "assets/images/VARUNA.jpeg"
  },
  {
    slug: "vasaka",
    name: "Vasaka",
    scientific: "Justicia adhatoda",
    rawLabel: "leaves",
    description: "We supply premium quality Vasaka leaves in raw form for manufacturers, traders, wholesalers & exporters worldwide.",
    forms: ["Whole Leaves", "Cut Leaves", "Leaf Pieces", "Leaf Powder"],
    packing: ["500g", "1kg", "5kg", "10kg", "25kg", "50kg+"],
    icon: "fa-leaf",
    imageBase: "assets/herbs/vasaka",
    catalogImage: "assets/images/VASAKA.jpeg"
  }
];
